version: '3.9'

services: 
  database:
    image: postgres
    container_name: any_container_name
    restart: always
    ports:
      - 1234:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local